spring:
  application:
    name: classroom-account
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/store
    username: ${POSTGRES_USER:store}
    password: ${POSTGRES_PASSWORD:store123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: account
  jpa:
    properties:
      hibernate:
        default_schema: account

springdoc:
  api-docs:
    path: /accounts/v3/api-docs
  swagger-ui:
    path: /accounts/swagger-ui.html


management:
  endpoints:
    web:
      base-path: /accounts/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka/



